#all: pcpsp QOLpcpsp cumulative
all: QOLpcpsp

LR = LagrangianHeuristic
INC = /usr/local/gurobi/6.5.1/include/
LIB = /usr/local/gurobi/6.5.1/lib/

# dependency generation
DEPDIR := .d
$(shell mkdir -p $(DEPDIR)/source >/dev/null)
$(shell mkdir -p $(DEPDIR)/$(LR) >/dev/null)
$(shell mkdir -p $(DEPDIR)/QOL/lagrangian >/dev/null)
DEPFLAGS = -MT $@ -MMD -MP -MF $(DEPDIR)/$*.Td
POSTCOMPILE = mv -f $(DEPDIR)/$*.Td $(DEPDIR)/$*.d


CXXFLAGS= -fno-stack-protector -g $(DEPFLAGS)
# choose flags for debugging vs best performance
#CXXFLAGS+=-D_GLIBCXX_DEBUG
CXXFLAGS+=-O3 -DNDEBUG

include QOL/Makefile
CPPFLAGS+= -I$(CPLEX_ROOT)/concert/include
CXXFLAGS+=-fopenmp
CPPFLAGS+=-DIL_STD  -Wno-sign-compare
#QOL_LIBS:= -L$(wildcard $(CPLEX_ROOT)/concert/lib/*/static_pic) -lconcert -lilocplex $(QOL_LIBS) #-lgurobi_c++ -lgurobi$(GUROBI_VER)
QOL_LIBS:= -L/opt/ibm/ILOG/CPLEX_Studio127/cplex/lib/x86-64_linux/static_pic -lilocplex -lconcert -lcplex -lm -lpthread -L/opt/ibm/ILOG/CPLEX_Studio127/concert/lib/x86-64_linux/static_pic -lilocplex -lconcert -lcplex -lm -lpthread $(QOL_LIBS) #-lgurobi_c++ -lgurobi$(GUROBI_VER)
CPPFLAGS+= -I./include -I. -I./$(LR)
$(QOL_LIB): $(wildcard $(QOL_DIR)/*.h $(QOL_DIR)/*.cpp)
	cd $(QOL_DIR); make

LAPSO_SRC=source/Particle.cpp $(wildcard QOL/lagrangian/[^d]*.cpp)
CPPFLAGS+= -I QOL/lagrangian
#anyoption.cpp QOL/lagrangian/VolVolume.cpp QOL/lagrangian/CpuTime
SRC=source/daten.cpp source/network.cpp source/boostMaxFlow.cpp source/CumulativeModel.cpp source/util.cpp source/MaxClosure_PP.cpp $(wildcard source/MaxClosure_B*.cpp) source/MaxClosureFactory.cpp source/UpitSolver.cpp source/graph.cpp source/SinglePSolver.cpp source/Preprocess.cpp source/SinglePModel.cpp source/SolutionMerger.cpp $(LAPSO_SRC) #$(LR)/solver.cpp $(LR)/mip.cpp $(LR)/ACO_solution.cpp $(LR)/Timer.cc $(LR)/Random.cc $(LR)/MaxClosure_NetworkFlow_LR.cpp $(LR)/pheromones.cpp source/lr_graph.cpp $(LR)/solver_functions.cpp source/solver_interface.cpp source/MaxClosure_NetworkFlow.cpp $(LAPSO_SRC)
OBJ=$(patsubst %.cpp,%.o,$(SRC))

LIBS = -L${LIB}$ -lgurobi_c++ -lpthread -lm -lgurobi65

%.o: %.cpp $(DEPDIR)/%.d
.cpp.o:
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@; $(POSTCOMPILE);

pcpsp: $(OBJ) $(QOL_LIB) source/pcpsp.o
	$(CXX) $(CPPFLAGS) $(CXXFLAGS)  -o $@ $^ $(QOL_LIBS)

libpp.so: $(OBJ)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -shared -o $@ $^ $(QOL_LIBS)

cumulative: $(OBJ) source/main.o
	$(CXX) $(CPPFLAGS) $(CXXFLAGS)  -o $@ $^ $(QOL_LIBS)

bz_algorithm: $(OBJ) source/rlp.o source/lpr_bz.o source/bz.o
	$(CXX) $(CPPFLAGS) $(CXXFLAGS)  -o $@ $^ $(QOL_LIBS)

lraco_opbs: $(OBJ) $(LR)/lraco_opbs.o
	$(CXX) $(CPPFLAGS) $(CXXFLAGS)  -o $@ $^ $(QOL_LIBS)

max_flow: $(OBJ) source/max_flow_no_st.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -o $@ $^

gen_graph: source/gengraph.cpp
	$(CXX) source/gengraph.cpp -o gen_graph

QOLpcpsp: $(OBJ) $(QOL_LIB) source/QOLpcpsp.o
	$(CXX) $(CPPFLAGS) $(CXXFLAGS)  -o $@ $^ $(QOL_LIBS)

clean::
	-rm -f source/*.o QOL/lagrangian/*.o $(LR)/*.o


$(DEPDIR)/%.d: ;
.PRECIOUS: $(DEPDIR)/%.d

-include $(patsubst %,$(DEPDIR)/%.d,$(basename $(SRC)))
